/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * T3DLvlConvertor.java
 *
 * Created on 26 avr. 2009, 12:53:28
 */

package ut3converter2.ihm.t3d;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ut3converter2.Installation;
import ut3converter2.Main;
import ut3converter2.UTGames;
import ut3converter2.convert.Level.ut2004.T3dU1UT99ToUT2k4;
import ut3converter2.ihm.Display2;
import ut3converter2.tools.T3DLevelNameChanger;
import ut3converter2.tools.T3DBrushTranformPerm;
import ut3converter2.tools.T3DLevelScaler;
import ut3converter2.tools.T3DLvlMoverPort;
import ut3converter2.tools.umc.UMCReader;

/**
 *
 * @author Hyperion
 */
public class T3DLvlConvertor extends javax.swing.JDialog {

    File t3dlvl;
    File outputfile;
    double scalefactor=1D;
    
    /** Creates new form T3DLvlConvertor */
    public T3DLvlConvertor(java.awt.Frame parent, File t3dlvl) {
        super(parent);
        initComponents();
        this.t3dlvl = t3dlvl;
        this.outputfile = new File(t3dlvl.getParent() + "\\"+ t3dlvl.getName().split("\\.")[0]+"-Converted.t3d");
        jtft3dlvl.setText(t3dlvl.getAbsolutePath());
        jtft3dout.setText(outputfile.getAbsolutePath());
    }

    //public static final Object[] defumc=new Object[]{true,new String[]{"UT2004-Coop","UT2004-Default"},"UT2004-Default"};
    public T3DLvlConvertor(java.awt.Frame parent, File t3dlvl,Object umcfiles[],String []scalefactors,int defaultfactor) {
        super(parent);
        initComponents();
        this.t3dlvl = t3dlvl;
        this.outputfile = new File(t3dlvl.getParent() + "\\"+ t3dlvl.getName().split("\\.")[0]+"-Converted.t3d");
        jtft3dlvl.setText(t3dlvl.getAbsolutePath());
        jtft3dout.setText(outputfile.getAbsolutePath());
        jcbumc.setEnabled(Boolean.valueOf(umcfiles[0].toString()));
        jcbumc.setModel(new DefaultComboBoxModel((String [])(umcfiles[1])));
        jcbumc.setSelectedItem(umcfiles[2].toString());
        jcbScaleFactor.setModel(new DefaultComboBoxModel(scalefactors));
        jcbScaleFactor.setSelectedIndex(defaultfactor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jLabel1 = new javax.swing.JLabel();
        jtft3dlvl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtft3dout = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbScaleFactor = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcbumc = new javax.swing.JComboBox();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jbtnConv = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Input T3D Level file:");

        jtft3dlvl.setEnabled(false);

        jLabel2.setText("Output T3D Level file:");

        jtft3dout.setEnabled(false);

        jLabel3.setText("Scale Factor:");

        jcbScaleFactor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "0.8 (UT2004 -> U1/UT)", "1", "1.25 (U1/UT -> UT2004)", "1.5", "1.75", "2" }));
        jcbScaleFactor.setSelectedIndex(3);

        jLabel4.setText("Conversion type:");

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtft3dlvl, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jtft3dout, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbumc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbScaleFactor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(71, 71, 71))))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtft3dlvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtft3dout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbScaleFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbumc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jXPanel1, java.awt.BorderLayout.CENTER);

        jbtnConv.setText("Convert");
        jbtnConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConvActionPerformed(evt);
            }
        });
        jXPanel2.add(jbtnConv);

        jbtnCancel.setText("Close");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        jXPanel2.add(jbtnCancel);

        getContentPane().add(jXPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvActionPerformed

        this.scalefactor = Double.valueOf(jcbScaleFactor.getSelectedItem().toString().split("\\(")[0]);
        try {

            File tr = File.createTempFile("Transformed", ".t3d");
            tr.deleteOnExit();
            if(t3dlvl!=null)
            {
                T3DBrushTranformPerm t3dt = new T3DBrushTranformPerm(t3dlvl, tr);
                t3dt.setBShowLog(true);
                t3dt.convert();
                try {
                    Thread.sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Display2.class.getName()).log(Level.SEVERE, null, ex);
                }

                File tr2 = File.createTempFile("MoverConv", ".t3d");
                tr2.deleteOnExit();

                T3DLvlMoverPort tm =new T3DLvlMoverPort(tr, tr2);
                tm.setBShowLog(true);
                tm.convert();
                try {
                    Thread.sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Display2.class.getName()).log(Level.SEVERE, null, ex);
                }

                File tr3 = File.createTempFile("ScaledMap", ".t3d");
                tr3.deleteOnExit();

                T3DLevelScaler tls = new T3DLevelScaler(tr2, tr3, scalefactor);
                tls.setScalestaticmeshes(false); //Doesn't scale mover staticmeshes as the  mover brushes/volumes have ever been scaled.
                tls.setBShowLog(true);
                tls.scale();

                File tr4 =  File.createTempFile("myLevelConv", ".t3d");
                tr4.deleteOnExit();

                //TODO Being able to use UT99 too
                T3dU1UT99ToUT2k4 ctt = new T3dU1UT99ToUT2k4(tr3, tr4, UTGames.U1);
                //ctt.setUsesimplename_snds(true);
                ctt.convert();

                File tr5 =  File.createTempFile("myLevelNew", ".t3d");
                tr5.deleteOnExit();
                T3DLevelNameChanger lnc = new T3DLevelNameChanger(tr4, tr5);
                lnc.setBShowLog(true);
                lnc.replace();

                File umcfile = new File(Installation.getInstallDirectory(Main.class).getAbsolutePath()+"\\conf\\"+jcbumc.getSelectedItem().toString());
                //File a = new File(Installation.getInstallDirectory(Main.class).getAbsolutePath()+"\\conf\\u1.txt");
                UMCReader umcr = new UMCReader(umcfile,tr5,outputfile);
                umcr.setBShowLog(true);
                umcr.replace();
                tr.delete();
                tr2.delete();
                tr3.delete();
                tr4.delete();
                tr5.delete();
                JOptionPane.showMessageDialog(null, "<html>Map have been converted to :<br>" + outputfile.getAbsolutePath()+"</html>", "Operation sucessful", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (IOException ex) {
            Logger.getLogger(Display2.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jbtnConvActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnConv;
    private javax.swing.JComboBox jcbScaleFactor;
    private javax.swing.JComboBox jcbumc;
    private javax.swing.JTextField jtft3dlvl;
    private javax.swing.JTextField jtft3dout;
    // End of variables declaration//GEN-END:variables

}
