/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJInternalFrame.java
 *
 * Created on 20 mars 2010, 12:05:59
 */

package ut3converter2.ihm;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.FileWriter;
import java.io.FilterOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JFrame;

/**
 *
 * @author Hyperion
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {

    private boolean logFile;
    private String fileName;

    /** Creates new form NewJInternalFrame */
    public NewJInternalFrame() {
        initComponents();
        PrintStream aPrintStream  =
       new PrintStream(
         new FilteredStream(
           new ByteArrayOutputStream()));
        System.setOut(aPrintStream); // catches System.out messages
            if (true) {
                System.setErr(aPrintStream); // catches error messages
            }

        aTextArea.setForeground(Color.black);
        aTextArea.setBackground(Color.orange);
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image im = tk.getImage("myicon.gif");
        this.setResizable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        aTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jbtnClearLog = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jcbSize = new javax.swing.JComboBox();

        aTextArea.setColumns(20);
        aTextArea.setRows(5);
        jScrollPane1.setViewportView(aTextArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jbtnClearLog.setText("Clear");
        jPanel1.add(jbtnClearLog);

        jButton1.setText("Save log ...");
        jPanel1.add(jButton1);

        jcbSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jcbSize);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnClearLog;
    private javax.swing.JComboBox jcbSize;
    // End of variables declaration//GEN-END:variables

    class FilteredStream extends FilterOutputStream {
        public FilteredStream(OutputStream aStream) {
            super(aStream);
          }

        public void write(byte b[]) throws IOException {
            String aString = new String(b);
            aTextArea.append(aString);
        }

        public void write(byte b[], int off, int len) throws IOException {
            String aString = new String(b , off , len);
            aTextArea.append(aString);
            if (logFile) {
                FileWriter aWriter = new FileWriter(fileName, true);
                aWriter.write(aString);
                aWriter.close();
            }
        }
    }
}
