/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settings.java
 *
 * Created on 18 sept. 2008, 10:26:51
 */

package ut3converter2.ihm;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ut3converter2.Configuration;
import ut3converter2.RegistryReader;
import ut3converter2.UTGames;

/**
 *
 * @author Hyperion
 */
public class Settings extends javax.swing.JDialog {


    Configuration conf;

    /** Creates new form Settings */
    public Settings(java.awt.Frame parent, Configuration conf) {
        super(parent);
        initComponents();
        this.conf = conf;
        loadconfig(conf);
    }

    public void loadconfig(Configuration conf)
    {
        File f;
        f = conf.getDeuxExRootFolder();
        if(f.exists()){jtfdeusexfolder.setText(conf.getDeuxExRootFolder().getAbsolutePath());}
        else{jtfdeusexfolder.setText("Not Found!");}

        f = conf.getU1RootFolder();
        if(f.exists()){jtfu1folder.setText(f.getAbsolutePath());}
        else{jtfu1folder.setText("Not Found!");}

        f = conf.getUT2003RootFolder();
        if(f.exists()){jtfut2003folder.setText(f.getAbsolutePath());}
        else{jtfut2003folder.setText("Not Found!");}

        f = conf.getU2RootFolder();
        if(f.exists()){jtfu2folder.setText(f.getAbsolutePath());}
        else{jtfu2folder.setText("Not Found!");}

        f = conf.getUT99RootFolder();
        if(f.exists()){jtfut99folder.setText(f.getAbsolutePath());}
        else{jtfut99folder.setText("Not Found!");}

        f = conf.getUT2004RootFolder();
        if(f.exists()){jtfut2004folder.setText(f.getAbsolutePath());}
        else{jtfut2004folder.setText("Not Found!");}

        f = conf.getUT3RootFolder();
        if(f.exists()){jtfut3folder.setText(f.getAbsolutePath());}
        else{jtfut3folder.setText("Not Found!");}
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfu1folder = new javax.swing.JTextField();
        jbtnunreal1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfu2folder = new javax.swing.JTextField();
        jbtnunreal2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfut99folder = new javax.swing.JTextField();
        jbtnut99 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfut2003folder = new javax.swing.JTextField();
        jbtnut2003 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfut2004folder = new javax.swing.JTextField();
        jbtnut2004 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfdeusexfolder = new javax.swing.JTextField();
        jbtndeusex = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtfut3folder = new javax.swing.JTextField();
        jbtnut3 = new javax.swing.JButton();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jButton6 = new javax.swing.JButton();
        jBtnAutoDetect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UT3 Converter settings");
        setResizable(false);
        getContentPane().add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jXPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("UT games root folders:"));

        jLabel1.setText("Unreal 1 Folder:");

        jtfu1folder.setEditable(false);
        jtfu1folder.setToolTipText("e.g.: \"C:/Games/Unreal1\"");

        jbtnunreal1.setText("Change");
        jbtnunreal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnunreal1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Unreal 2 Folder:");

        jtfu2folder.setEditable(false);

        jbtnunreal2.setText("Change");
        jbtnunreal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnunreal2ActionPerformed(evt);
            }
        });

        jLabel3.setText("UT99 Folder:");

        jtfut99folder.setEditable(false);
        jtfut99folder.setToolTipText("e.g. : \"C:\\Program Files\\Unreal Tournament\"");

        jbtnut99.setText("Change");
        jbtnut99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnut99ActionPerformed(evt);
            }
        });

        jLabel4.setText("UT2003 Folder:");

        jtfut2003folder.setEditable(false);
        jtfut2003folder.setToolTipText("e.g. : \"C:\\Program Files\\Unreal Tournament 2003\"");

        jbtnut2003.setText("Change");
        jbtnut2003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnut2003ActionPerformed(evt);
            }
        });

        jLabel5.setText("UT2004 Folder:");

        jtfut2004folder.setEditable(false);
        jtfut2004folder.setToolTipText("e.g. : \"C:\\Program Files\\Unreal Tournament 2004\"");

        jbtnut2004.setText("Change");
        jbtnut2004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnut2004ActionPerformed(evt);
            }
        });

        jLabel6.setText("Deus Ex Folder:");

        jtfdeusexfolder.setEditable(false);

        jbtndeusex.setText("Change");
        jbtndeusex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeusexActionPerformed(evt);
            }
        });

        jLabel7.setText("UT3 Folder:");

        jtfut3folder.setEditable(false);

        jbtnut3.setText("Change");
        jbtnut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfu2folder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jtfut99folder, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jtfut2003folder, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jtfut2004folder, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jtfu1folder, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jtfut3folder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jtfdeusexfolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnut3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtndeusex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnut2004, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnut2003, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnut99, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnunreal2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnunreal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfu1folder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnunreal1)))
                .addGap(15, 15, 15)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfu2folder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnunreal2))
                .addGap(15, 15, 15)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfut99folder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnut99))
                .addGap(15, 15, 15)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfut2003folder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnut2003))
                .addGap(15, 15, 15)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfut2004folder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnut2004))
                .addGap(15, 15, 15)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfdeusexfolder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndeusex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfut3folder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnut3))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jXPanel1, java.awt.BorderLayout.CENTER);

        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jXPanel2.add(jButton6);

        jBtnAutoDetect.setText("Auto-Detect");
        jBtnAutoDetect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAutoDetectActionPerformed(evt);
            }
        });
        jXPanel2.add(jBtnAutoDetect);

        getContentPane().add(jXPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtnunreal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnunreal1ActionPerformed
        JFileChooser jfc = new JFileChooser(new File(jtfu1folder.getText()));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select the Unreal 1 root folder");
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            File f = new File(jfc.getSelectedFile().getAbsolutePath()+File.separator+"/System/");
            if(f.exists()){conf.setU1RootFolder(jfc.getSelectedFile());
                JOptionPane.showMessageDialog(null,UTGames.U1_name_short+ " folder set. \nMake sure you have latest Unreal 1 Patch installed from www.oldunreal.com." ,"Check Unreal 1 version", JOptionPane.WARNING_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"This is not a valid "+UTGames.U1_name_short+" root folder","Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        loadconfig(conf);
}//GEN-LAST:event_jbtnunreal1ActionPerformed

    private void jbtnunreal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnunreal2ActionPerformed
        JFileChooser jfc = new JFileChooser(new File(jtfu1folder.getText()));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select the Unreal 2 root folder");
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            File f = new File(jfc.getSelectedFile().getAbsolutePath()+File.separator+"/System/");
            if(f.exists()){conf.setU2RootFolder(jfc.getSelectedFile());
            }
            else{
                JOptionPane.showMessageDialog(null,"This is not a valid "+UTGames.U2_name_short+" root folder","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadconfig(conf);
    }//GEN-LAST:event_jbtnunreal2ActionPerformed

    private void jbtnut99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnut99ActionPerformed
        JFileChooser jfc = new JFileChooser(new File(jtfu1folder.getText()));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select the Unreal Tournament root folder");
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            File f = new File(jfc.getSelectedFile().getAbsolutePath()+File.separator+"/System/");
            if(f.exists()){conf.setUT99RootFolder(jfc.getSelectedFile());
            }
            else{
                JOptionPane.showMessageDialog(null,"This is not a valid "+UTGames.UT99_name_short+" root folder","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadconfig(conf);
    }//GEN-LAST:event_jbtnut99ActionPerformed

    private void jbtnut2003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnut2003ActionPerformed
        JFileChooser jfc = new JFileChooser(new File(jtfu1folder.getText()));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select the Unreal Tournament 2003 root folder");
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            File f = new File(jfc.getSelectedFile().getAbsolutePath()+File.separator+"/System/");
            if(f.exists()){conf.setU1RootFolder(jfc.getSelectedFile());
            }
            else{
                JOptionPane.showMessageDialog(null,"This is not a valid "+UTGames.UT2003_name_short+" root folder","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadconfig(conf);
    }//GEN-LAST:event_jbtnut2003ActionPerformed

    private void jbtnut2004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnut2004ActionPerformed
        JFileChooser jfc = new JFileChooser(new File(jtfu1folder.getText()));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select the Unreal Tournament 2004 root folder");
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            File f = new File(jfc.getSelectedFile().getAbsolutePath()+File.separator+"/System/");
            if(f.exists()){conf.setUT2004RootFolder(jfc.getSelectedFile());
            }
            else{
                JOptionPane.showMessageDialog(null,"This is not a valid "+UTGames.UT2004_name_short+" root folder","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadconfig(conf);
    }//GEN-LAST:event_jbtnut2004ActionPerformed

    private void jbtndeusexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeusexActionPerformed
        JFileChooser jfc = new JFileChooser(new File(jtfu1folder.getText()));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select the Deux Ex root folder");
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            File f = new File(jfc.getSelectedFile().getAbsolutePath()+File.separator+"/System/");
            if(f.exists()){conf.setDeuxExRootFolder(jfc.getSelectedFile());
            }
            else{
                JOptionPane.showMessageDialog(null,"This is not a valid "+UTGames.DE_name_short+" root folder","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadconfig(conf);
    }//GEN-LAST:event_jbtndeusexActionPerformed

    private void jBtnAutoDetectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAutoDetectActionPerformed
        try {
            boolean bFound = false;
            String tmp = RegistryReader.getUTxFolderPath(UTGames.U1);

            if (tmp != null) {
                bFound = true;
                conf.setU1RootFolder(new File(tmp));
            }
            tmp = RegistryReader.getUTxFolderPath(UTGames.UT99);
            if (tmp != null) {
                bFound = true;
                conf.setUT99RootFolder(new File(tmp));
            }
            tmp = RegistryReader.getUTxFolderPath(UTGames.UT2003);
            if (tmp != null) {
                bFound = true;
                conf.setUT2003RootFolder(new File(tmp));
            }
            tmp = RegistryReader.getUTxFolderPath(UTGames.UT2004);
            if (tmp != null) {
                bFound = true;
                conf.setUT2004RootFolder(new File(tmp));
            }
            tmp = RegistryReader.getUTxFolderPath(UTGames.DeusEx);
            if (tmp != null) {
                bFound = true;
                conf.setDeuxExRootFolder(new File(tmp));
            }
            
            if(!bFound){
                JOptionPane.showMessageDialog(this, "No unreal game was found. Use manual setup.", "Games not detected.", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }

        loadconfig(conf);
    }//GEN-LAST:event_jBtnAutoDetectActionPerformed

    private void jbtnut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnut3ActionPerformed
       JFileChooser jfc = new JFileChooser(new File(jtfu1folder.getText()));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select the UT3 root folder");
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            conf.setUT3RootFolder(jfc.getSelectedFile());
        }
        loadconfig(conf);
    }//GEN-LAST:event_jbtnut3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAutoDetect;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private javax.swing.JButton jbtndeusex;
    private javax.swing.JButton jbtnunreal1;
    private javax.swing.JButton jbtnunreal2;
    private javax.swing.JButton jbtnut2003;
    private javax.swing.JButton jbtnut2004;
    private javax.swing.JButton jbtnut3;
    private javax.swing.JButton jbtnut99;
    private javax.swing.JTextField jtfdeusexfolder;
    private javax.swing.JTextField jtfu1folder;
    private javax.swing.JTextField jtfu2folder;
    private javax.swing.JTextField jtfut2003folder;
    private javax.swing.JTextField jtfut2004folder;
    private javax.swing.JTextField jtfut3folder;
    private javax.swing.JTextField jtfut99folder;
    // End of variables declaration//GEN-END:variables

}
