/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowResult.java
 *
 * Created on 1 mai 2009, 08:21:32
 */

package ut3converter2.ihm.map;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXHyperlink;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author Hyperion
 */
public class ShowResult extends javax.swing.JInternalFrame {

    GlobalInstructions gi;
    BufferedImage test;
    /** Creates new form ShowResult */
    public ShowResult(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        this.setVisible(true);
        this.setSize(400, 300);
        this.setResizable(true);
        //this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        //Main.d2.
    }

    public void setTitleName(String tile)
    {
        super.setTitle(title);
    }
    public ShowResult(java.awt.Frame parent, boolean modal,GlobalInstructions gi) {
        //super(parent, modal);
        initComponents();
        String title="";
        this.gi = gi;
        Instructions insts=null;
        ArrayList <Instruction>alinst;
        Instruction inst=null;
        JXHyperlink jhp=null;
        int maxinstructions=0;
        int numtab=gi.getSize();


        for(int i=0;i<gi.getSize();i++)
        {
            JXPanel jxp = new JXPanel();
            jxp.setLayout(new java.awt.GridLayout(i, 1));

            insts = gi.getAlglinst().get(i);
            alinst = insts.getAlinst();
            jxp.setLayout(new java.awt.GridLayout(alinst.size(), 1));
            if(alinst.size()>maxinstructions){maxinstructions=alinst.size();}

            for(int j=0;j<alinst.size();j++)
            {
                inst = alinst.get(j);
                jxp.add(inst.getInstru_data());
                /*
                if(inst.hasImage())
                {
                    final Instruction inst2;
                    inst2 = inst;
                    jhp = new JXHyperlink();
                    jhp.setForeground(Color.red);
                    jhp.setToolTipText("Click to see sample picture");
                    jhp.setText(inst.getMessage());
                    jhp.addActionListener(new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        ShowImage si = new ShowImage(null, true, inst2.getImage());
                        si.setVisible(true);
                        //JOptionPane.showMessageDialog(null, "test", "title", WIDTH, new javax.swing.ImageIcon(getClass().getResource(inst2.getImage())));
                    }
                });
                    jxp.add(jhp);
                }
                else
                {
                    jxp.add(new JLabel(inst.getMessage()));
                }*/
            }
            
            if(insts.hasTitle()){title = insts.getTitle();}
            else { title = "Step "+i;}

            jTabbedPane1.add(title,jxp);
        }

        //this.setLocationRelativeTo(null);
        this.setSize(200+numtab*100, 20+maxinstructions*30);

    }

    private static void open(URI uri) {
        if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                try {
                        desktop.browse(uri);
                } catch (IOException e) {
                }
        } else {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jXPanel1.add(jButton1);

        jButton3.setText("<-Previous");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jXPanel1.add(jButton3);

        jButton2.setText("Next->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jXPanel1.add(jButton2);

        getContentPane().add(jXPanel1, java.awt.BorderLayout.SOUTH);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int numcurtab = jTabbedPane1.getSelectedIndex();
        int numtotoftabs = jTabbedPane1.getTabCount();
        if(numtotoftabs>(numcurtab+1))
        {
            jTabbedPane1.setSelectedIndex(numcurtab+1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int numcurtab = jTabbedPane1.getSelectedIndex();
        int numtotoftabs = jTabbedPane1.getTabCount();
        if((numcurtab-1)>=0)
        {
            jTabbedPane1.setSelectedIndex(numcurtab-1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables

}
