/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowImage.java
 *
 * Created on 1 mai 2009, 11:46:35
 */

package ut3converter2.ihm.map;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Hyperion
 */
public class ShowImage extends javax.swing.JDialog {

    /** Creates new form ShowImage */
    public ShowImage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ShowImage(java.awt.Frame parent, boolean modal,String image,int x,int y) {
        super(parent, modal);
        initComponents();
        ImageIcon ii = new javax.swing.ImageIcon(getClass().getResource(image));
        jXLabel1.setIcon(ii);
        //this.setLocationRelativeTo(null);
        this.setLocation(x, y);
        this.setSize(ii.getIconWidth()+15, ii.getIconHeight()+35);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(jXLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowImage dialog = new ShowImage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jXLabel1;
    // End of variables declaration//GEN-END:variables

}
